{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.product.name }}
  labels:
    {{- include "atlas2-helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.product.name }}
spec:
  selector:
    matchLabels:
      {{- include "atlas2-helm-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.product.name }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
{{- end }}
