{{- with .Values.postgres.product }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  ports:
    - port: 5432
      name: postgres
    {{- if .exporter.enabled }}
    - port: {{ .exporter.port | default 9187 }}
      name: metrics
      targetPort: metrics
    {{- end }}
  clusterIP: None
  selector:
    app: {{ .name }}
{{- end }}
