syntax = "proto3";

package order;

option go_package = "./;order";

import "google/protobuf/timestamp.proto";

message Order {
  int64 order_id = 1;
  int64 user_id = 2;
  double total = 3;
  double final = 4;
  bool is_shipped = 5;
  google.protobuf.Timestamp create_date = 6;
  repeated OrderDetail order_details = 7;
}

message OrderDetail {
  int64 detail_id = 1;
  int64 order_id = 2;
  int64 product_id = 3;
  int32 item = 4;
  double final = 5;
  google.protobuf.Timestamp create_date = 6;
}

message ListOrdersRequest {}

message ListOrdersResponse {
  repeated Order orders = 1;
}

// Update Order Status Request
message UpdateOrderStatusRequest {
  int64 order_id = 1;
  bool is_shipped = 2;
}

// Update Order Status Response
message UpdateOrderStatusResponse {
  string message = 1;
}

// Create Order Request
message CreateOrderRequest {
  int64 user_id = 1;
  repeated OrderItem items = 2;
}

message OrderItem {
  int64 product_id = 1;
  int32 quantity = 2;
  double price = 3;
}

// Create Order Response
message CreateOrderResponse {
  int64 order_id = 1;
  string message = 2;
}

service OrderService {
  rpc ListOrders (ListOrdersRequest) returns (ListOrdersResponse);
  // Admin - Sipariş durumunu günceller
  rpc UpdateOrderStatus (UpdateOrderStatusRequest) returns (UpdateOrderStatusResponse);
  // Yeni sipariş oluşturur
  rpc CreateOrder (CreateOrderRequest) returns (CreateOrderResponse);
}

